[project]
name = "poo-proyecto"
version = "0.1.0"
description = "Proyecto entregable para asignatura Programación Orientada a Objetos"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mysql-connector-python>=9.1.0",
    "python-dotenv>=1.0.1",
]
